### ISSUE TITLE
Some issues with the sample...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nextdimension/superlightstack#1]
1. The "data to persist" isn't quite persistant. Upon pressing "goto view X" , and then pressing the back button, the data didn't get re-shown. That's not how it works on fragments and activities, unless you close them...
2. I can't exit the first phase. Pressing back doesn't do anything there.

**Comment by nextdimension** [comment]
The example was just quickly done to show how it can be used but I see how these issues could cause you problems.

1.) You are correct, I will change this behaviour.

If you go back to the first view the data won't display in the edit text, simply because I have not set it to do so, but that is an easy thing to do, it just requires setting the data on the edit text and that more closely resembles the default Android behaviour.

2) I don't call super method of "onBackPressed"  in the sample, also easy to fix.

I will issue these fixes shortly, thanks

**Comment by nextdimension** [comment]
Done

**Comment by AndroidDeveloperLB** [comment]
So both fixed? Thanks
